import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/models/RegisterModal";
import LoginModal from "./components/models/LoginModal";
import RentModel from "./components/models/RentModel";
import ToasterProvider from "./providers/ToasterProvider";
import getCurrentUser from "./actions/getCurrentUser";

const font =Nunito({
  subsets : ["latin"],
});

export const metadata: Metadata = {
  title: "myProject",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser=await getCurrentUser();
 
  return (
    <html lang="en">
      
      <body
        className={font.className}>
         <ClientOnly>
          <ToasterProvider/>
          <RentModel/>
          <LoginModal/>
          <RegisterModal/>
          <Navbar currentUser={currentUser}/>
         </ClientOnly>
         <div className="pb-20 pt-28">
            {children}
         </div>
      </body>
    </html>
  )
}
